# This is a sample workflow to help working with API specs based on APIx Manager, main steps:
# 1. add secrets for your github actions, e.g. APIX_OAUTH2_CLIENT_SECRET in {your_github_repo}/settings/secrets/actions
# 2. add below workflow in your github repo.

name: APIx
on:
  push:
    branches:
      - "*"
    tags: [v*.*-*]

env:
  API_SPEC: openapi/spec2.json
  APIX_SERVICE: meraki_dashboard
  APIX_CLI_NAME: apiregistryctl
  APIX_CLI_DOWNLOAD_URL: https://static.production.devnetcloud.com/libs/apixmanager-cli/latest/linux/amd64/apiregistryctl
  APIX_CLI_VERSION: latest
  APIX_HOST: https://devnet-testing.cisco.com
  APIX_BASE_PATH: /v1/apiregistry-cisco
  APIX_AUTH_TYPE: oauth2
  APIX_OAUTH2_GRANT_TYPE: client_credentials
  APIX_OAUTH2_TOKEN_URL: https://auth-devnet-stg.cisco.com/v1/auth/oauth/token
  APIX_OAUTH2_CLIENT_ID: bu-service-client
  APIX_OAUTH2_CLIENT_SECRET: ${{ secrets.APIX_OAUTH2_CLIENT_SECRET }}
  GIT_EMAIL: abc@gmail.com
  CHANGE_LOG_FILE_NAME: change_log.md
  RELEASE_REVISON: 10

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # analyze API specs
  # by default, it fails if there is any findings in error severity.
  # additionally, `--fail-below-score int` could be used to fail this step with specified minimal target score.
  
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: APIx - Install CLI
        uses: supplypike/setup-bin@v1
        with:
          uri: ${{ env.APIX_CLI_DOWNLOAD_URL }}
          name: ${{ env.APIX_CLI_NAME }}
          version: ${{ env.APIX_CLI_VERSION }}
      - name: Set tag env
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Echo tag env
        run: |
          echo ${{ env.RELEASE_TAG }}        
        
      - id: parse-tags
        name: Parse tags
        uses: actions/github-script@v6
        with:
          script: |
            const items = "${{ env.RELEASE_TAG }}".split('-')
            console.log(items)
            core.setOutput('version', items[0])
            core.setOutput('revision', items[1])          
            
      - name: APIx - Analyze API Spec
        run: |
          apiregistryctl analyze ${{ env.API_SPEC }}
  diff:
    #needs: [ analyze ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: APIx - Install CLI
        uses: supplypike/setup-bin@v1
        with:
          uri: ${{ env.APIX_CLI_DOWNLOAD_URL }}
          name: ${{ env.APIX_CLI_NAME }}
          version: ${{ env.APIX_CLI_VERSION }}
      - name: APIx - Diff API SPec
        run: |
          # generate the change log
          apiregistryctl diff ${{ env.API_SPEC }} -s ${{ env.APIX_SERVICE }} --latest -o markdown | tee ${{ env.CHANGE_LOG_FILE_NAME }}
          
      - name: Read change log and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat ${{ env.CHANGE_LOG_FILE_NAME }})                       # <--- Read release.md (Provide correct path as per your repo)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"         # <--- Set environment variable
          
      - name: Upload change log to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.CHANGE_LOG_FILE_NAME }}
          asset_name: ${{ env.CHANGE_LOG_FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: $r
          
  release:
    # Use `needs` to define prerequisite jobs, e.g. only upload when step `analyze` and `diff` is successful.
    #needs: [ analyze, diff]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Get current git branch name    
        uses: actions/checkout@v3
        with:
          run: echo "CURRENT_BRANCH=${git symbolic-ref --short HEAD}" >> $GITHUB_ENV
          ref: ${{ env.CURRENT_BRANCH }}
      - name: APIx - Install CLI
        uses: supplypike/setup-bin@v1
        with:
          uri: ${{ env.APIX_CLI_DOWNLOAD_URL }}
          name: ${{ env.APIX_CLI_NAME }}
          version: ${{ env.APIX_CLI_VERSION }}
      - name: Set tag env
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Echo tag env
        run: |
          echo ${{ env.RELEASE_TAG }}                
      - id: parse-tags
        name: Parse tags
        uses: actions/github-script@v6
        with:
          script: |
            const items = "${{ env.RELEASE_TAG }}".split('-')
            console.log(items)
            core.setOutput('version', items[0])
            core.setOutput('revision', items[1])
      - name: Set version env
        run: echo "RELEASE_VERSION=${{steps.parse-tags.outputs.version}}" >> $GITHUB_ENV
      - name: Set revision env
        run: echo "RELEASE_REVISON=${{steps.parse-tags.outputs.revision}}" >> $GITHUB_ENV        
#       - name: APIx - Upload API SPec
#         run: |
#           apiregistryctl service uploadspec ${{ env.API_SPEC }} -s ${{ env.APIX_SERVICE }} --revision ${{ env.RELEASE_REVISON }}

      - name: Generate change log
        run: |
          # analyze spec log output to terminal and save it to change log file
          apiregistryctl diff ${{ env.API_SPEC }} -s ${{ env.APIX_SERVICE }} --latest -o markdown | tee ${{ env.CHANGE_LOG_FILE_NAME }}

      - name: Read release.md and use it as a body of new release
        id: read_release
        shell: bash
        run: |
          r=$(cat ${{ env.CHANGE_LOG_FILE_NAME }})                       # <--- Read release.md (Provide correct path as per your repo)
          r="${r//'%'/'%25'}"                               # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"                             # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"                             # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"         # <--- Set environment variable

          file: target/release/${{ env.CHANGE_LOG_FILE_NAME }}
          asset_name: ${{ env.CHANGE_LOG_FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: $r
        
      - name: Upload change log to Release
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ github.ref }}
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
            
          
      - name: Pubslih change log      
        run: |
          # Stage the file, commit and push
          git config user.name "GitHub Actions Bot"
          git config user.email  ${{ env.GIT_EMAIL }}          
          git add ${{ env.CHANGE_LOG_FILE_NAME }}
          git diff-index --quiet HEAD || git commit -m "new change log commit"
          echo "Current branch: ${{ env.CURRENT_BRANCH }}"
          git push origin ${{ env.CURRENT_BRANCH }} --force
